###########################################################
# Makefile generated by xIDE                               
#                                                          
# Project: spp_dev_b
# Configuration: Release
# Generated: 星期二 二月 22 17:22:24 2011
#                                                          
# WARNING: Do not edit this file. Any changes will be lost 
#          when the project is rebuilt.                    
#                                                          
###########################################################

OUTPUT=spp_dev_b
OUTDIR=F:/spp_dev_b
HARDWARE_INDEX=1
DEFS=

DEBUGTRANSPORT=[SPI|LPT1|No]
EXECUTION_MODE=vm
STACKSIZE=0
TRANSPORT=raw
FIRMWARE=unified
FIRMWAREIMAGE=

LIBS=-lconnection -lspp -lregion -lservice -lbdaddr 
INPUTS=\
      spp_button.button\
      main.c\
      spp_dev_init.c\
      spp_dev_inquire.c\
      spp_dev_auth.c\
      spp_dev_led.c\
      spp_button.c\
      spp_dev_init.h\
      spp_dev_private.h\
      spp_dev_inquire.h\
      spp_dev_auth.h\
      spp_dev_led.h\
      spp_dev_b.psr\
      spp_button.h

-include spp_dev_b.mak
include $(BLUELAB)/Makefile.vm
